[project]
name = "pyclack-lib"
version = "1.0.2"
description = "A Python library for building beautiful interactive CLI prompts with clack-style UX."
readme = "README.md"
authors = [
    { name = "Maddox-RVS", email = "" }
]
requires-python = ">=3.10"
dependencies = [
    "colorama>=0.4.6",
    "readchar>=4.2.2",
    "rich>=15.0.0",
    "strsimpy>=0.2.1",
]

[tool.uv.build-backend]
module-name = "pyclack"

[build-system]
requires = ["uv_build>=0.11.9,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 200

[tool.ruff.lint]
select = ["E", "F"] # keep only basic errors
ignore = ["I", "E701"] # ignore import sorting rules, and single line if statements

[tool.pyright]
typeCheckingMode = "basic"
