from .symbols import Symbols, Symbol, SpinnerSymbols

class Style:
    '''
    A class representing the style attributes for a theme, including background color, foreground color, 
    and text formatting options such as bold, underline, italic, and strikethrough.
    '''

    def __init__(self, 
        bg_color: str | None = None,
        fg_color: str | None = None,
        bold: bool = False,
        underline: bool = False,
        italic: bool = False,
        strikethrough: bool = False,
        dim: bool = False):
        '''
        Initialize a Style object with the given attributes.
        All color attributes can either be a string representing a color name, a hexadecimal color code, or None for default terminal colors.

        Args:
            bg_color (str, optional): Background color of the theme.
            fg_color (str, optional): Foreground color of the theme.
            bold (bool, optional): Whether the text is bold.
            underline (bool, optional): Whether the text is underlined.
            italic (bool, optional): Whether the text is italicized.
            strikethrough (bool, optional): Whether the text has a strikethrough.
            dim (bool, optional): Whether to dim the text color
        '''

        self.bg_color: str | None = bg_color
        self.fg_color: str | None = fg_color
        self.bold: bool = bold
        self.underline: bool = underline
        self.italic: bool = italic
        self.strikethrough: bool = strikethrough
        self.dim: bool = dim

class Theme:
    '''
    A class representing a theme, which consists of various styles for different elements and symbols used in the rendering process.
    '''

    def __init__(self, 
        active: Style,
        submit: Style,
        cancel: Style,
        error: Style,
        info: Style,
        muted: Style,
        text: Style,
        cursor: Style,
        symbols: Symbols):
        '''
        Initialize a Theme object with the given styles.

        Args:
            active (Style): Style for active elements.
            submit (Style): Style for submit elements.
            cancel (Style): Style for cancel elements.
            error (Style): Style for error elements.
            info (Style): Style for info elements.
            muted (Style): Style for muted elements.
            text (Style): Style for general text.
            cursor (Style): Style for the cursor.
            symbols (Symbols): Symbols to use in the theme.
        '''

        self.active: Style = active
        self.submit: Style = submit
        self.cancel: Style = cancel
        self.error: Style = error
        self.info: Style = info
        self.muted: Style = muted
        self.text: Style = text
        self.cursor: Style = cursor
        self.symbols: Symbols = symbols

class Themes:
    '''
    A class representing a collection of themes, including a default theme.
    '''

    DEFAULT: Theme = Theme(
        active   = Style(fg_color='cyan'),
        submit   = Style(fg_color='green'),
        cancel   = Style(fg_color='red'),
        error    = Style(fg_color='yellow'),
        info     = Style(fg_color='blue'),
        muted    = Style(fg_color='bright_black'),
        text     = Style(fg_color='white'),
        cursor   = Style(fg_color='bright_black', bg_color='white'),
        symbols  = Symbols(
            step_marker_active                       = Symbol('◆', '*'),
            step_marker_cancel                       = Symbol('■', 'x'),
            step_marker_error                        = Symbol('▲', 'x'),
            step_marker_submit                       = Symbol('◇', 'o'),
            connector_bar_start                      = Symbol('┌', 'T'),
            connector_bar_vertical                   = Symbol('│', '|'),
            connector_bar_end                        = Symbol('└', '—'),
            selection_widget_radio_active            = Symbol('●', '>'),
            selection_widget_radio_inactive          = Symbol('○', ' '),
            selection_widget_checkbox_active         = Symbol('◻', '[•]'),
            selection_widget_checkbox_selected       = Symbol('◼', '[+]'),
            selection_widget_checkbox_inactive       = Symbol('◻', '[ ]'),
            selection_widget_password_mask           = Symbol('▪', '•'),
            box_drawing_horizontal_bar               = Symbol('─', '-'),
            box_drawing_vertical_bar                 = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded     = Symbol('╮', '+'),
            box_drawing_left_connector               = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded  = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded      = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded   = Symbol('╰', '+'),
            box_drawing_top_right_corner             = Symbol('┐', '+'),
            box_drawing_bottom_right_corner          = Symbol('┘', '+'),
            box_drawing_top_left_corner              = Symbol('┌', '+'),
            box_drawing_bottom_left_corner           = Symbol('└', '+'),
            log_level_info                           = Symbol('●', '•'),
            log_level_success                        = Symbol('◆', '*'),
            log_level_warn                           = Symbol('▲', '!'),
            log_level_error                          = Symbol('■', 'x'),
            spinner                                  = SpinnerSymbols(
                                                        unicode_symbols=('◒', '◐', '◓', '◑'), 
                                                        ascii_symbols=('•', 'o', 'O', '0')),
            progress_light=Symbol('─', '-'),
            progress_heavy=Symbol('━', '='),
            progress_block=Symbol('█', '#')
        )
    )

    DARK: Theme = Theme(
        active   = Style(fg_color='#61AFEF'),
        submit   = Style(fg_color='#98C379'),
        cancel   = Style(fg_color='#E06C75'),
        error    = Style(fg_color='#E5C07B'),
        info     = Style(fg_color='#56B6C2'),
        muted    = Style(fg_color='#5C6370'),
        text     = Style(fg_color='#ABB2BF'),
        cursor   = Style(fg_color='#282C34', bg_color='#ABB2BF'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('▶', '>'),
            step_marker_cancel                     = Symbol('■', 'x'),
            step_marker_error                      = Symbol('▲', '!'),
            step_marker_submit                     = Symbol('✓', 'v'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('●', '(*)'),
            selection_widget_radio_inactive        = Symbol('○', '( )'),
            selection_widget_checkbox_active       = Symbol('◻', '[·]'),
            selection_widget_checkbox_selected     = Symbol('◼', '[x]'),
            selection_widget_checkbox_inactive     = Symbol('◻', '[ ]'),
            selection_widget_password_mask         = Symbol('•', '*'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('●', 'i'),
            log_level_success                      = Symbol('◆', 'v'),
            log_level_warn                         = Symbol('▲', '!'),
            log_level_error                        = Symbol('■', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('█', '#')
        )
    )

    LIGHT: Theme = Theme(
        active   = Style(fg_color='#2563EB'),
        submit   = Style(fg_color='#059669'),
        cancel   = Style(fg_color='#DC2626'),
        error    = Style(fg_color='#D97706'),
        info     = Style(fg_color='#0891B2'),
        muted    = Style(fg_color='#6B7280'),
        text     = Style(fg_color='#1F2937'),
        cursor   = Style(fg_color='#FFFFFF', bg_color='#1F2937'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('✧', '*'),
            step_marker_cancel                     = Symbol('◌', 'x'),
            step_marker_error                      = Symbol('△', '!'),
            step_marker_submit                     = Symbol('✦', '+'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('⦿', '(*)'),
            selection_widget_radio_inactive        = Symbol('◌', '( )'),
            selection_widget_checkbox_active       = Symbol('▣', '[x]'),
            selection_widget_checkbox_selected     = Symbol('⬔', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('⬚', '[ ]'),
            selection_widget_password_mask         = Symbol('⋄', '*'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('✧', 'i'),
            log_level_success                      = Symbol('✦', 'v'),
            log_level_warn                         = Symbol('△', '!'),
            log_level_error                        = Symbol('⨯', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◌', '◍', '◎', '●'), ascii_symbols=('.', 'o', 'O', 'o')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▪', '#')
        )
    )

    FOCUS: Theme = Theme(
        active   = Style(fg_color='#2563EB'),
        submit   = Style(fg_color='#16A34A'),
        cancel   = Style(fg_color='#DC2626'),
        error    = Style(fg_color='#D97706'),
        info     = Style(fg_color='#0891B2'),
        muted    = Style(fg_color='#9CA3AF'),
        text     = Style(fg_color='#111827'),
        cursor   = Style(fg_color='#FFFFFF', bg_color='#111827'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('⊙', '>'),
            step_marker_cancel                     = Symbol('⊗', 'x'),
            step_marker_error                      = Symbol('⊖', '!'),
            step_marker_submit                     = Symbol('⊕', 'v'),
            connector_bar_start                    = Symbol('╔', '+'),
            connector_bar_vertical                 = Symbol('║', '|'),
            connector_bar_end                      = Symbol('╚', '+'),
            selection_widget_radio_active          = Symbol('⦿', '(*)'),
            selection_widget_radio_inactive        = Symbol('⭘', '( )'),
            selection_widget_checkbox_active       = Symbol('▣', '[x]'),
            selection_widget_checkbox_selected     = Symbol('▤', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('▢', '[ ]'),
            selection_widget_password_mask         = Symbol('∙', '*'),
            box_drawing_horizontal_bar             = Symbol('═', '='),
            box_drawing_vertical_bar               = Symbol('║', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('╗', '+'),
            box_drawing_bottom_right_corner        = Symbol('╝', '+'),
            box_drawing_top_left_corner            = Symbol('╔', '+'),
            box_drawing_bottom_left_corner         = Symbol('╚', '+'),
            log_level_info                         = Symbol('⊙', 'i'),
            log_level_success                      = Symbol('⊕', 'v'),
            log_level_warn                         = Symbol('⊖', '!'),
            log_level_error                        = Symbol('⊗', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◤', '◥', '◢', '◣'), ascii_symbols=('<', '^', '>', 'v')),
            progress_light                         = Symbol('═', '='),
            progress_heavy                         = Symbol('═', '='),
            progress_block                         = Symbol('█', '#')
        )
    )

    HIGH_CONTRAST: Theme = Theme(
        active   = Style(fg_color='#3B82F6'),
        submit   = Style(fg_color='#22C55E'),
        cancel   = Style(fg_color='#EF4444'),
        error    = Style(fg_color='#F59E0B'),
        info     = Style(fg_color='#06B6D4'),
        muted    = Style(fg_color='#52525B'),
        text     = Style(fg_color='#F8F9FA'),
        cursor   = Style(fg_color='#000000', bg_color='#F8F9FA'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('➜', '>'),
            step_marker_cancel                     = Symbol('✖', 'x'),
            step_marker_error                      = Symbol('▲', '!'),
            step_marker_submit                     = Symbol('✔', 'v'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('⏺', '(*)'),
            selection_widget_radio_inactive        = Symbol('⭘', '( )'),
            selection_widget_checkbox_active       = Symbol('█', '[x]'),
            selection_widget_checkbox_selected     = Symbol('▓', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('░', '[ ]'),
            selection_widget_password_mask         = Symbol('█', '*'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('ⓘ', 'i'),
            log_level_success                      = Symbol('✔', 'v'),
            log_level_warn                         = Symbol('▲', '!'),
            log_level_error                        = Symbol('✖', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('█', '▓', '▒', '░', '▒', '▓'), ascii_symbols=('#', '=', '-', ' ', '-', '=')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('█', '#')
        )
    )

    NEBULA: Theme = Theme(
        active   = Style(fg_color='#89b4fa'),
        submit   = Style(fg_color='#a6e3a1'),
        cancel   = Style(fg_color='#f38ba8'),
        error    = Style(fg_color='#f9e2af'),
        info     = Style(fg_color='#89dceb'),
        muted    = Style(fg_color='#6c7086'),
        text     = Style(fg_color='#cdd6f4'),
        cursor   = Style(fg_color='#1e1e2e', bg_color='#89b4fa'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('❯', '>'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('✖', '!'),
            step_marker_submit                     = Symbol('✔', 'v'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('◉', '(*)'),
            selection_widget_radio_inactive        = Symbol('◯', '( )'),
            selection_widget_checkbox_active       = Symbol('☑', '[x]'),
            selection_widget_checkbox_selected     = Symbol('☒', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('☐', '[ ]'),
            selection_widget_password_mask         = Symbol('•', '*'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('✦', 'i'),
            log_level_success                      = Symbol('✔', 'v'),
            log_level_warn                         = Symbol('▲', '!'),
            log_level_error                        = Symbol('✖', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◜', '◝', '◞', '◟'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('█', '#')
        )
    )

    SEPIA: Theme = Theme(
        active   = Style(fg_color='#E5A93C'),
        submit   = Style(fg_color='#8A9A5B'),
        cancel   = Style(fg_color='#C85A32'),
        error    = Style(fg_color='#E07A5F'),
        info     = Style(fg_color='#D4A373'),
        muted    = Style(fg_color='#8C7A6B'),
        text     = Style(fg_color='#F5E6D3'),
        cursor   = Style(fg_color='#2C1D11', bg_color='#F5E6D3'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('☞', '>'),
            step_marker_cancel                     = Symbol('⛌', 'x'),
            step_marker_error                      = Symbol('☡', '!'),
            step_marker_submit                     = Symbol('❦', 'v'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('✦', '(*)'),
            selection_widget_radio_inactive        = Symbol('✧', '( )'),
            selection_widget_checkbox_active       = Symbol('❖', '[x]'),
            selection_widget_checkbox_selected     = Symbol('◈', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('◇', '[ ]'),
            selection_widget_password_mask         = Symbol('♦', '*'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('☙', 'i'),
            log_level_success                      = Symbol('⚜', 'v'),
            log_level_warn                         = Symbol('☡', '!'),
            log_level_error                        = Symbol('✢', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◴', '◵', '◶', '◷'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▪', '#')
        )
    )

    OCEAN: Theme = Theme(
        active   = Style(fg_color='#0EA5E9'),
        submit   = Style(fg_color='#14B8A6'),
        cancel   = Style(fg_color='#F43F5E'),
        error    = Style(fg_color='#FB923C'),
        info     = Style(fg_color='#38BDF8'),
        muted    = Style(fg_color='#64748B'),
        text     = Style(fg_color='#E0F2FE'),
        cursor   = Style(fg_color='#082F49', bg_color='#7DD3FC'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('⚓', '*'),
            step_marker_cancel                     = Symbol('☒', 'x'),
            step_marker_error                      = Symbol('☡', '!'),
            step_marker_submit                     = Symbol('⛵', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('⚓', '*'),
            selection_widget_radio_inactive        = Symbol('○', ' '),
            selection_widget_checkbox_active       = Symbol('☐', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('☑', '[x]'),
            selection_widget_checkbox_inactive     = Symbol('☐', '[ ]'),
            selection_widget_password_mask         = Symbol('≈', '~'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('☵', 'i'),
            log_level_success                      = Symbol('⚓', '*'),
            log_level_warn                         = Symbol('☡', '!'),
            log_level_error                        = Symbol('☒', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('⠁', '⠂', '⠄', '⠂'), ascii_symbols=('.', ''', '.', ''')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▓', '#')
        )
    )

    FOREST: Theme = Theme(
        active   = Style(fg_color='#22C55E'),
        submit   = Style(fg_color='#4ADE80'),
        cancel   = Style(fg_color='#DC2626'),
        error    = Style(fg_color='#CA8A04'),
        info     = Style(fg_color='#10B981'),
        muted    = Style(fg_color='#57534E'),
        text     = Style(fg_color='#D9F2E3'),
        cursor   = Style(fg_color='#052E1A', bg_color='#86EFAC'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('❦', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('⚠', '!'),
            step_marker_submit                     = Symbol('❧', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('❋', '*'),
            selection_widget_radio_inactive        = Symbol('❊', ' '),
            selection_widget_checkbox_active       = Symbol('☘', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('❦', '[#]'),
            selection_widget_checkbox_inactive     = Symbol('☘', '[ ]'),
            selection_widget_password_mask         = Symbol('∘', '.'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('❧', 'i'),
            log_level_success                      = Symbol('❦', '*'),
            log_level_warn                         = Symbol('⚠', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◜', '◝', '◞', '◟'), ascii_symbols=('.', 'o', '.', 'o')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▓', '#')
        )
    )

    SUNSET: Theme = Theme(
        active   = Style(fg_color='#FB923C'),
        submit   = Style(fg_color='#F59E0B'),
        cancel   = Style(fg_color='#E11D48'),
        error    = Style(fg_color='#FBBF24'),
        info     = Style(fg_color='#FB7185'),
        muted    = Style(fg_color='#78716C'),
        text     = Style(fg_color='#FFE8D6'),
        cursor   = Style(fg_color='#431407', bg_color='#FDBA74'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('➤', '>'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('▲', '!'),
            step_marker_submit                     = Symbol('➜', '-'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┇', ':'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('➤', '>'),
            selection_widget_radio_inactive        = Symbol('➔', ' '),
            selection_widget_checkbox_active       = Symbol('▷', '[>]'),
            selection_widget_checkbox_selected     = Symbol('▶', '[»]'),
            selection_widget_checkbox_inactive     = Symbol('▷', '[ ]'),
            selection_widget_password_mask         = Symbol('»', '>'),
            box_drawing_horizontal_bar             = Symbol('┅', '='),
            box_drawing_vertical_bar               = Symbol('┇', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('➜', '>'),
            log_level_success                      = Symbol('➤', '*'),
            log_level_warn                         = Symbol('➔', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('▹', '▸', '▹', '▸'), ascii_symbols=('>', '>', '>', '>')),
            progress_light                         = Symbol('┅', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▶', '#')
        )
    )

    CYBERPUNK: Theme = Theme(
        active   = Style(fg_color='#F0ABFC'),
        submit   = Style(fg_color='#22D3EE'),
        cancel   = Style(fg_color='#FB7185'),
        error    = Style(fg_color='#FACC15'),
        info     = Style(fg_color='#A78BFA'),
        muted    = Style(fg_color='#64748B'),
        text     = Style(fg_color='#E9D5FF'),
        cursor   = Style(fg_color='#0A0A0F', bg_color='#F0ABFC'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('▣', '*'),
            step_marker_cancel                     = Symbol('⌦', 'x'),
            step_marker_error                      = Symbol('⌁', '!'),
            step_marker_submit                     = Symbol('▤', 'o'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('⏺', '*'),
            selection_widget_radio_inactive        = Symbol('⭘', ' '),
            selection_widget_checkbox_active       = Symbol('▢', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('▩', '[#]'),
            selection_widget_checkbox_inactive     = Symbol('▢', '[ ]'),
            selection_widget_password_mask         = Symbol('▓', '#'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('ⓘ', 'i'),
            log_level_success                      = Symbol('▣', '*'),
            log_level_warn                         = Symbol('⌁', '!'),
            log_level_error                        = Symbol('⌦', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▓', '#')
        )
    )

    MONOCHROME: Theme = Theme(
        active   = Style(fg_color='#FFFFFF'),
        submit   = Style(fg_color='#D4D4D4'),
        cancel   = Style(fg_color='#737373'),
        error    = Style(fg_color='#A3A3A3'),
        info     = Style(fg_color='#E5E5E5'),
        muted    = Style(fg_color='#525252'),
        text     = Style(fg_color='#D4D4D4'),
        cursor   = Style(fg_color='#0A0A0A', bg_color='#FFFFFF'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('◉', '*'),
            step_marker_cancel                     = Symbol('⊗', 'x'),
            step_marker_error                      = Symbol('⊖', '!'),
            step_marker_submit                     = Symbol('◎', 'o'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('◉', '*'),
            selection_widget_radio_inactive        = Symbol('◌', ' '),
            selection_widget_checkbox_active       = Symbol('◍', '[·]'),
            selection_widget_checkbox_selected     = Symbol('◉', '[●]'),
            selection_widget_checkbox_inactive     = Symbol('◌', '[ ]'),
            selection_widget_password_mask         = Symbol('∙', '.'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('◎', 'i'),
            log_level_success                      = Symbol('◉', '*'),
            log_level_warn                         = Symbol('◐', '!'),
            log_level_error                        = Symbol('⊗', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◜', '◠', '◝', '◞', '◡', '◟'), ascii_symbols=('.', 'o', 'O', 'o', '.', ' ')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('●', '#')
        )
    )

    AUTUMN: Theme = Theme(
        active   = Style(fg_color='#D97706'),
        submit   = Style(fg_color='#A16207'),
        cancel   = Style(fg_color='#B91C1C'),
        error    = Style(fg_color='#CA8A04'),
        info     = Style(fg_color='#C2410C'),
        muted    = Style(fg_color='#78350F'),
        text     = Style(fg_color='#FDE7C8'),
        cursor   = Style(fg_color='#431407', bg_color='#FB923C'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('◈', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('◭', '!'),
            step_marker_submit                     = Symbol('◇', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('◈', '*'),
            selection_widget_radio_inactive        = Symbol('◇', ' '),
            selection_widget_checkbox_active       = Symbol('◇', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('◈', '[♦]'),
            selection_widget_checkbox_inactive     = Symbol('◇', '[ ]'),
            selection_widget_password_mask         = Symbol('♦', '*'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('◇', 'i'),
            log_level_success                      = Symbol('◈', '*'),
            log_level_warn                         = Symbol('◭', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◇', '◈', '◆', '◈'), ascii_symbols=('o', '+', '#', '+')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('◆', '#')
        )
    )

    ARCTIC: Theme = Theme(
        active   = Style(fg_color='#38BDF8'),
        submit   = Style(fg_color='#5EEAD4'),
        cancel   = Style(fg_color='#FB7185'),
        error    = Style(fg_color='#FDE047'),
        info     = Style(fg_color='#7DD3FC'),
        muted    = Style(fg_color='#94A3B8'),
        text     = Style(fg_color='#F0F9FF'),
        cursor   = Style(fg_color='#0C2A3D', bg_color='#BAE6FD'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('❄', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('⚠', '!'),
            step_marker_submit                     = Symbol('❆', 'o'),
            connector_bar_start                    = Symbol('╔', '+'),
            connector_bar_vertical                 = Symbol('║', '|'),
            connector_bar_end                      = Symbol('╚', '+'),
            selection_widget_radio_active          = Symbol('❉', '*'),
            selection_widget_radio_inactive        = Symbol('❊', ' '),
            selection_widget_checkbox_active       = Symbol('◇', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('❄', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('◇', '[ ]'),
            selection_widget_password_mask         = Symbol('·', '.'),
            box_drawing_horizontal_bar             = Symbol('═', '='),
            box_drawing_vertical_bar               = Symbol('║', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('╗', '+'),
            box_drawing_bottom_right_corner        = Symbol('╝', '+'),
            box_drawing_top_left_corner            = Symbol('╔', '+'),
            box_drawing_bottom_left_corner         = Symbol('╚', '+'),
            log_level_info                         = Symbol('❆', 'i'),
            log_level_success                      = Symbol('❄', '*'),
            log_level_warn                         = Symbol('⚠', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('❄', '❅', '❆', '❅'), ascii_symbols=('*', '+', '*', '+')),
            progress_light                         = Symbol('═', '='),
            progress_heavy                         = Symbol('═', '='),
            progress_block                         = Symbol('❄', '#')
        )
    )

    VOLCANO: Theme = Theme(
        active   = Style(fg_color='#F97316'),
        submit   = Style(fg_color='#FACC15'),
        cancel   = Style(fg_color='#DC2626'),
        error    = Style(fg_color='#EA580C'),
        info     = Style(fg_color='#FB923C'),
        muted    = Style(fg_color='#57534E'),
        text     = Style(fg_color='#FFE4D6'),
        cursor   = Style(fg_color='#1C0A00', bg_color='#F87171'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('▲', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('⚠', '!'),
            step_marker_submit                     = Symbol('△', 'o'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('●', '*'),
            selection_widget_radio_inactive        = Symbol('○', ' '),
            selection_widget_checkbox_active       = Symbol('◭', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('◮', '[^]'),
            selection_widget_checkbox_inactive     = Symbol('◭', '[ ]'),
            selection_widget_password_mask         = Symbol('◆', '*'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('◬', 'i'),
            log_level_success                      = Symbol('▲', '*'),
            log_level_warn                         = Symbol('⚠', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('╱', '╲', '╱', '╲'), ascii_symbols=('/', '\\', '/', '\\')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▲', '#')
        )
    )

    ROYAL: Theme = Theme(
        active   = Style(fg_color='#7C3AED'),
        submit   = Style(fg_color='#C4B454'),
        cancel   = Style(fg_color='#B91C1C'),
        error    = Style(fg_color='#C4B454'),
        info     = Style(fg_color='#A78BFA'),
        muted    = Style(fg_color='#6D6875'),
        text     = Style(fg_color='#EDE9FE'),
        cursor   = Style(fg_color='#1E1033', bg_color='#C4B454'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('♛', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('☡', '!'),
            step_marker_submit                     = Symbol('♕', 'o'),
            connector_bar_start                    = Symbol('╔', '+'),
            connector_bar_vertical                 = Symbol('║', '|'),
            connector_bar_end                      = Symbol('╚', '+'),
            selection_widget_radio_active          = Symbol('♦', '*'),
            selection_widget_radio_inactive        = Symbol('♢', ' '),
            selection_widget_checkbox_active       = Symbol('♤', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('♠', '[♠]'),
            selection_widget_checkbox_inactive     = Symbol('♤', '[ ]'),
            selection_widget_password_mask         = Symbol('♛', '*'),
            box_drawing_horizontal_bar             = Symbol('═', '='),
            box_drawing_vertical_bar               = Symbol('║', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('╗', '+'),
            box_drawing_bottom_right_corner        = Symbol('╝', '+'),
            box_drawing_top_left_corner            = Symbol('╔', '+'),
            box_drawing_bottom_left_corner         = Symbol('╚', '+'),
            log_level_info                         = Symbol('♢', 'i'),
            log_level_success                      = Symbol('♕', '*'),
            log_level_warn                         = Symbol('☡', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◐', '◓', '◑', '◒'), ascii_symbols=('o', 'O', 'o', 'O')),
            progress_light                         = Symbol('═', '='),
            progress_heavy                         = Symbol('═', '='),
            progress_block                         = Symbol('♠', '#')
        )
    )

    MINT: Theme = Theme(
        active   = Style(fg_color='#2DD4BF'),
        submit   = Style(fg_color='#34D399'),
        cancel   = Style(fg_color='#FB7185'),
        error    = Style(fg_color='#FBBF24'),
        info     = Style(fg_color='#5EEAD4'),
        muted    = Style(fg_color='#78716C'),
        text     = Style(fg_color='#E6FFFA'),
        cursor   = Style(fg_color='#042F2E', bg_color='#99F6E4'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('◯', '*'),
            step_marker_cancel                     = Symbol('⊗', 'x'),
            step_marker_error                      = Symbol('◐', '!'),
            step_marker_submit                     = Symbol('○', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('●', '*'),
            selection_widget_radio_inactive        = Symbol('◯', ' '),
            selection_widget_checkbox_active       = Symbol('◯', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('●', '[o]'),
            selection_widget_checkbox_inactive     = Symbol('◯', '[ ]'),
            selection_widget_password_mask         = Symbol('。', '.'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('○', 'i'),
            log_level_success                      = Symbol('●', '*'),
            log_level_warn                         = Symbol('◐', '!'),
            log_level_error                        = Symbol('⊗', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('.', 'o', 'O', 'o', '.', ' '), ascii_symbols=('.', 'o', 'O', 'o', '.', ' ')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('●', '#')
        )
    )

    DESERT: Theme = Theme(
        active   = Style(fg_color='#D8A657'),
        submit   = Style(fg_color='#B08968'),
        cancel   = Style(fg_color='#B5533C'),
        error    = Style(fg_color='#E3B23C'),
        info     = Style(fg_color='#C9A66B'),
        muted    = Style(fg_color='#8A7B5C'),
        text     = Style(fg_color='#F3E5C3'),
        cursor   = Style(fg_color='#3B2A1A', bg_color='#E3B23C'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('▲', '^'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('☀', '!'),
            step_marker_submit                     = Symbol('△', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('●', '*'),
            selection_widget_radio_inactive        = Symbol('○', ' '),
            selection_widget_checkbox_active       = Symbol('▭', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('▬', '[=]'),
            selection_widget_checkbox_inactive     = Symbol('▭', '[ ]'),
            selection_widget_password_mask         = Symbol('∴', '.'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('☀', 'i'),
            log_level_success                      = Symbol('▲', '^'),
            log_level_warn                         = Symbol('☀', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◐', '◓', '◑', '◒'), ascii_symbols=('o', 'O', 'o', 'O')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▤', '#')
        )
    )

    MIDNIGHT: Theme = Theme(
        active   = Style(fg_color='#6366F1'),
        submit   = Style(fg_color='#34D399'),
        cancel   = Style(fg_color='#F87171'),
        error    = Style(fg_color='#FBBF24'),
        info     = Style(fg_color='#818CF8'),
        muted    = Style(fg_color='#475569'),
        text     = Style(fg_color='#C7D2FE'),
        cursor   = Style(fg_color='#0B1026', bg_color='#818CF8'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('★', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('✱', '!'),
            step_marker_submit                     = Symbol('☆', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('✦', '*'),
            selection_widget_radio_inactive        = Symbol('✧', ' '),
            selection_widget_checkbox_active       = Symbol('☆', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('★', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('☆', '[ ]'),
            selection_widget_password_mask         = Symbol('✦', '*'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('✧', 'i'),
            log_level_success                      = Symbol('★', '*'),
            log_level_warn                         = Symbol('✱', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('✶', '✸', '✹', '✺'), ascii_symbols=('*', '+', '*', 'x')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('★', '#')
        )
    )

    PASTEL: Theme = Theme(
        active   = Style(fg_color='#A5B4FC'),
        submit   = Style(fg_color='#86EFAC'),
        cancel   = Style(fg_color='#FCA5A5'),
        error    = Style(fg_color='#FDE68A'),
        info     = Style(fg_color='#93C5FD'),
        muted    = Style(fg_color='#A1A1AA'),
        text     = Style(fg_color='#4B5563'),
        cursor   = Style(fg_color='#FFFFFF', bg_color='#C7D2FE'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('◉', '*'),
            step_marker_cancel                     = Symbol('⊗', 'x'),
            step_marker_error                      = Symbol('⊖', '!'),
            step_marker_submit                     = Symbol('◎', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('◉', '*'),
            selection_widget_radio_inactive        = Symbol('◌', ' '),
            selection_widget_checkbox_active       = Symbol('◍', '[·]'),
            selection_widget_checkbox_selected     = Symbol('◉', '[●]'),
            selection_widget_checkbox_inactive     = Symbol('◌', '[ ]'),
            selection_widget_password_mask         = Symbol('∙', '.'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('◎', 'i'),
            log_level_success                      = Symbol('◉', '*'),
            log_level_warn                         = Symbol('◐', '!'),
            log_level_error                        = Symbol('⊗', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◜', '◠', '◝', '◞', '◡', '◟'), ascii_symbols=('.', 'o', 'O', 'o', '.', ' ')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('●', '#')
        )
    )

    RETRO: Theme = Theme(
        active   = Style(fg_color='#FFB000'),
        submit   = Style(fg_color='#33FF33'),
        cancel   = Style(fg_color='#FF3333'),
        error    = Style(fg_color='#FFD700'),
        info     = Style(fg_color='#00FFFF'),
        muted    = Style(fg_color='#806000'),
        text     = Style(fg_color='#FFB000'),
        cursor   = Style(fg_color='#000000', bg_color='#FFB000'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('▶', '>'),
            step_marker_cancel                     = Symbol('X', 'x'),
            step_marker_error                      = Symbol('!', '!'),
            step_marker_submit                     = Symbol('-', '-'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('>', '>'),
            selection_widget_radio_inactive        = Symbol(' ', ' '),
            selection_widget_checkbox_active       = Symbol('[o]', '[o]'),
            selection_widget_checkbox_selected     = Symbol('[x]', '[x]'),
            selection_widget_checkbox_inactive     = Symbol('[ ]', '[ ]'),
            selection_widget_password_mask         = Symbol('#', '#'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('i', 'i'),
            log_level_success                      = Symbol('+', '+'),
            log_level_warn                         = Symbol('!', '!'),
            log_level_error                        = Symbol('X', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('|', '/', '-', '\\'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('#', '#')
        )
    )

    MATRIX: Theme = Theme(
        active   = Style(fg_color='#00FF41'),
        submit   = Style(fg_color='#00FF41'),
        cancel   = Style(fg_color='#FF0033'),
        error    = Style(fg_color='#39FF14'),
        info     = Style(fg_color='#00CC33'),
        muted    = Style(fg_color='#0D3B0D'),
        text     = Style(fg_color='#00FF41'),
        cursor   = Style(fg_color='#000000', bg_color='#00FF41'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('▮', '#'),
            step_marker_cancel                     = Symbol('╳', 'x'),
            step_marker_error                      = Symbol('▲', '!'),
            step_marker_submit                     = Symbol('▯', '-'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('▮', '#'),
            selection_widget_radio_inactive        = Symbol('▯', '-'),
            selection_widget_checkbox_active       = Symbol('▯', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('▮', '[#]'),
            selection_widget_checkbox_inactive     = Symbol('▯', '[ ]'),
            selection_widget_password_mask         = Symbol('▒', '%'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('▯', 'i'),
            log_level_success                      = Symbol('▮', '#'),
            log_level_warn                         = Symbol('▲', '!'),
            log_level_error                        = Symbol('╳', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('1', '0', '1', '0'), ascii_symbols=('1', '0', '1', '0')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▓', '#')
        )
    )

    CORAL: Theme = Theme(
        active   = Style(fg_color='#FF6F61'),
        submit   = Style(fg_color='#2EC4B6'),
        cancel   = Style(fg_color='#E71D36'),
        error    = Style(fg_color='#FF9F1C'),
        info     = Style(fg_color='#4CC9F0'),
        muted    = Style(fg_color='#6D6875'),
        text     = Style(fg_color='#FFE5DE'),
        cursor   = Style(fg_color='#3D0C02', bg_color='#FF9F1C'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('✺', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('✲', '!'),
            step_marker_submit                     = Symbol('✻', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('✺', '*'),
            selection_widget_radio_inactive        = Symbol('✧', ' '),
            selection_widget_checkbox_active       = Symbol('❁', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('✺', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('❁', '[ ]'),
            selection_widget_password_mask         = Symbol('∘', '.'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('✻', 'i'),
            log_level_success                      = Symbol('✺', '*'),
            log_level_warn                         = Symbol('✲', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('✢', '✣', '✤', '✥'), ascii_symbols=('*', '+', 'x', '+')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('✺', '#')
        )
    )

    STEEL: Theme = Theme(
        active   = Style(fg_color='#94A3B8'),
        submit   = Style(fg_color='#64B6AC'),
        cancel   = Style(fg_color='#EF4444'),
        error    = Style(fg_color='#F59E0B'),
        info     = Style(fg_color='#60A5FA'),
        muted    = Style(fg_color='#475569'),
        text     = Style(fg_color='#E2E8F0'),
        cursor   = Style(fg_color='#0F172A', bg_color='#CBD5E1'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('✚', '+'),
            step_marker_cancel                     = Symbol('✗', 'x'),
            step_marker_error                      = Symbol('✜', '!'),
            step_marker_submit                     = Symbol('✛', 'o'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('⊕', '+'),
            selection_widget_radio_inactive        = Symbol('⊙', ' '),
            selection_widget_checkbox_active       = Symbol('▧', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('▨', '[+]'),
            selection_widget_checkbox_inactive     = Symbol('▧', '[ ]'),
            selection_widget_password_mask         = Symbol('†', '+'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('✛', 'i'),
            log_level_success                      = Symbol('✚', '+'),
            log_level_warn                         = Symbol('✜', '!'),
            log_level_error                        = Symbol('✗', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('┤', '┘', '┴', '└', '├', '┌', '┬', '┐'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▨', '#')
        )
    )

    SAKURA: Theme = Theme(
        active   = Style(fg_color='#FDA4C0'),
        submit   = Style(fg_color='#86EFAC'),
        cancel   = Style(fg_color='#FB7185'),
        error    = Style(fg_color='#FBCFE8'),
        info     = Style(fg_color='#F9A8D4'),
        muted    = Style(fg_color='#A78B93'),
        text     = Style(fg_color='#FFF0F5'),
        cursor   = Style(fg_color='#4A1226', bg_color='#FBCFE8'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('❀', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('❃', '!'),
            step_marker_submit                     = Symbol('✿', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('❀', '*'),
            selection_widget_radio_inactive        = Symbol('◯', ' '),
            selection_widget_checkbox_active       = Symbol('✿', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('❀', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('✿', '[ ]'),
            selection_widget_password_mask         = Symbol('·', '.'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('✿', 'i'),
            log_level_success                      = Symbol('❀', '*'),
            log_level_warn                         = Symbol('❃', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('❀', '❁', '❃', '❁'), ascii_symbols=('*', 'o', '+', 'o')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('❀', '#')
        )
    )

    GALAXY: Theme = Theme(
        active   = Style(fg_color='#A78BFA'),
        submit   = Style(fg_color='#34D399'),
        cancel   = Style(fg_color='#F87171'),
        error    = Style(fg_color='#FBBF24'),
        info     = Style(fg_color='#818CF8'),
        muted    = Style(fg_color='#4C4664'),
        text     = Style(fg_color='#DDD6FE'),
        cursor   = Style(fg_color='#0B0521', bg_color='#A78BFA'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('✦', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('☄', '!'),
            step_marker_submit                     = Symbol('✧', 'o'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┇', ':'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('✳', '*'),
            selection_widget_radio_inactive        = Symbol('✶', ' '),
            selection_widget_checkbox_active       = Symbol('◇', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('✦', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('◇', '[ ]'),
            selection_widget_password_mask         = Symbol('·', '.'),
            box_drawing_horizontal_bar             = Symbol('┅', '='),
            box_drawing_vertical_bar               = Symbol('┇', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('✧', 'i'),
            log_level_success                      = Symbol('✦', '*'),
            log_level_warn                         = Symbol('☄', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('✦', '✧', '✩', '✧'), ascii_symbols=('*', '+', '*', '+')),
            progress_light                         = Symbol('┅', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▓', '#')
        )
    )

    TERRA: Theme = Theme(
        active   = Style(fg_color='#92703C'),
        submit   = Style(fg_color='#6B8E4E'),
        cancel   = Style(fg_color='#A13D2E'),
        error    = Style(fg_color='#C08A2E'),
        info     = Style(fg_color='#7A9E7E'),
        muted    = Style(fg_color='#6B5B4A'),
        text     = Style(fg_color='#EDE0C8'),
        cursor   = Style(fg_color='#2B1D0E', bg_color='#B08D57'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('❦', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('⚠', '!'),
            step_marker_submit                     = Symbol('❧', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('❋', '*'),
            selection_widget_radio_inactive        = Symbol('❊', ' '),
            selection_widget_checkbox_active       = Symbol('☘', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('❦', '[#]'),
            selection_widget_checkbox_inactive     = Symbol('☘', '[ ]'),
            selection_widget_password_mask         = Symbol('∘', '.'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('❧', 'i'),
            log_level_success                      = Symbol('❦', '*'),
            log_level_warn                         = Symbol('⚠', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◜', '◝', '◞', '◟'), ascii_symbols=('.', 'o', '.', 'o')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▓', '#')
        )
    )

    TWILIGHT: Theme = Theme(
        active   = Style(fg_color='#8B5CF6'),
        submit   = Style(fg_color='#F472B6'),
        cancel   = Style(fg_color='#FB7185'),
        error    = Style(fg_color='#FBBF24'),
        info     = Style(fg_color='#C084FC'),
        muted    = Style(fg_color='#6B5B95'),
        text     = Style(fg_color='#E9D5FF'),
        cursor   = Style(fg_color='#1A1030', bg_color='#C084FC'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('★', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('✱', '!'),
            step_marker_submit                     = Symbol('☆', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('┆', ':'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('✦', '*'),
            selection_widget_radio_inactive        = Symbol('✧', ' '),
            selection_widget_checkbox_active       = Symbol('☆', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('★', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('☆', '[ ]'),
            selection_widget_password_mask         = Symbol('✦', '*'),
            box_drawing_horizontal_bar             = Symbol('┄', '-'),
            box_drawing_vertical_bar               = Symbol('┆', ':'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('✧', 'i'),
            log_level_success                      = Symbol('★', '*'),
            log_level_warn                         = Symbol('✱', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('✶', '✸', '✹', '✺'), ascii_symbols=('*', '+', '*', 'x')),
            progress_light                         = Symbol('┄', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('★', '#')
        )
    )

    GOLD: Theme = Theme(
        active   = Style(fg_color='#D4AF37'),
        submit   = Style(fg_color='#C9A227'),
        cancel   = Style(fg_color='#8B0000'),
        error    = Style(fg_color='#B8860B'),
        info     = Style(fg_color='#E6C200'),
        muted    = Style(fg_color='#7A6A3A'),
        text     = Style(fg_color='#FFF3C4'),
        cursor   = Style(fg_color='#1A1400', bg_color='#D4AF37'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('◈', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('◭', '!'),
            step_marker_submit                     = Symbol('◇', 'o'),
            connector_bar_start                    = Symbol('╔', '+'),
            connector_bar_vertical                 = Symbol('║', '|'),
            connector_bar_end                      = Symbol('╚', '+'),
            selection_widget_radio_active          = Symbol('◈', '*'),
            selection_widget_radio_inactive        = Symbol('◇', ' '),
            selection_widget_checkbox_active       = Symbol('◇', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('◈', '[♦]'),
            selection_widget_checkbox_inactive     = Symbol('◇', '[ ]'),
            selection_widget_password_mask         = Symbol('♦', '*'),
            box_drawing_horizontal_bar             = Symbol('═', '='),
            box_drawing_vertical_bar               = Symbol('║', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('╗', '+'),
            box_drawing_bottom_right_corner        = Symbol('╝', '+'),
            box_drawing_top_left_corner            = Symbol('╔', '+'),
            box_drawing_bottom_left_corner         = Symbol('╚', '+'),
            log_level_info                         = Symbol('◇', 'i'),
            log_level_success                      = Symbol('◈', '*'),
            log_level_warn                         = Symbol('◭', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('◇', '◈', '◆', '◈'), ascii_symbols=('o', '+', '#', '+')),
            progress_light                         = Symbol('═', '='),
            progress_heavy                         = Symbol('═', '='),
            progress_block                         = Symbol('◆', '#')
        )
    )

    FROST: Theme = Theme(
        active   = Style(fg_color='#BFE9FF'),
        submit   = Style(fg_color='#C8F4E8'),
        cancel   = Style(fg_color='#FFB3C1'),
        error    = Style(fg_color='#FFF2B3'),
        info     = Style(fg_color='#E0F7FF'),
        muted    = Style(fg_color='#7C93A3'),
        text     = Style(fg_color='#F0FBFF'),
        cursor   = Style(fg_color='#0A2A3A', bg_color='#BFE9FF'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('❄', '*'),
            step_marker_cancel                     = Symbol('✕', 'x'),
            step_marker_error                      = Symbol('⚠', '!'),
            step_marker_submit                     = Symbol('❆', 'o'),
            connector_bar_start                    = Symbol('┌', '+'),
            connector_bar_vertical                 = Symbol('│', '|'),
            connector_bar_end                      = Symbol('└', '+'),
            selection_widget_radio_active          = Symbol('❉', '*'),
            selection_widget_radio_inactive        = Symbol('❊', ' '),
            selection_widget_checkbox_active       = Symbol('◇', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('❄', '[*]'),
            selection_widget_checkbox_inactive     = Symbol('◇', '[ ]'),
            selection_widget_password_mask         = Symbol('·', '.'),
            box_drawing_horizontal_bar             = Symbol('─', '-'),
            box_drawing_vertical_bar               = Symbol('│', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┐', '+'),
            box_drawing_bottom_right_corner        = Symbol('┘', '+'),
            box_drawing_top_left_corner            = Symbol('┌', '+'),
            box_drawing_bottom_left_corner         = Symbol('└', '+'),
            log_level_info                         = Symbol('❆', 'i'),
            log_level_success                      = Symbol('❄', '*'),
            log_level_warn                         = Symbol('⚠', '!'),
            log_level_error                        = Symbol('✕', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('❄', '❅', '❆', '❅'), ascii_symbols=('*', '+', '*', '+')),
            progress_light                         = Symbol('─', '-'),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('❄', '#')
        )
    )

    CRIMSON: Theme = Theme(
        active   = Style(fg_color='#DC143C'),
        submit   = Style(fg_color='#A83232'),
        cancel   = Style(fg_color='#FF073A'),
        error    = Style(fg_color='#B22222'),
        info     = Style(fg_color='#C0392B'),
        muted    = Style(fg_color='#5C1A1A'),
        text     = Style(fg_color='#FFD1D1'),
        cursor   = Style(fg_color='#1A0000', bg_color='#DC143C'),
        symbols  = Symbols(
            step_marker_active                     = Symbol('✚', '+'),
            step_marker_cancel                     = Symbol('✗', 'x'),
            step_marker_error                      = Symbol('✜', '!'),
            step_marker_submit                     = Symbol('✛', 'o'),
            connector_bar_start                    = Symbol('┏', '+'),
            connector_bar_vertical                 = Symbol('┃', '|'),
            connector_bar_end                      = Symbol('┗', '+'),
            selection_widget_radio_active          = Symbol('⊕', '+'),
            selection_widget_radio_inactive        = Symbol('⊙', ' '),
            selection_widget_checkbox_active       = Symbol('▧', '[ ]'),
            selection_widget_checkbox_selected     = Symbol('▨', '[+]'),
            selection_widget_checkbox_inactive     = Symbol('▧', '[ ]'),
            selection_widget_password_mask         = Symbol('†', '+'),
            box_drawing_horizontal_bar             = Symbol('━', '='),
            box_drawing_vertical_bar               = Symbol('┃', '|'),
            box_drawing_top_right_corner_rounded   = Symbol('╮', '+'),
            box_drawing_left_connector             = Symbol('├', '+'),
            box_drawing_bottom_right_corner_rounded = Symbol('╯', '+'),
            box_drawing_top_left_corner_rounded    = Symbol('╭', '+'),
            box_drawing_bottom_left_corner_rounded = Symbol('╰', '+'),
            box_drawing_top_right_corner           = Symbol('┓', '+'),
            box_drawing_bottom_right_corner        = Symbol('┛', '+'),
            box_drawing_top_left_corner            = Symbol('┏', '+'),
            box_drawing_bottom_left_corner         = Symbol('┗', '+'),
            log_level_info                         = Symbol('✛', 'i'),
            log_level_success                      = Symbol('✚', '+'),
            log_level_warn                         = Symbol('✜', '!'),
            log_level_error                        = Symbol('✗', 'x'),
            spinner                                = SpinnerSymbols(unicode_symbols=('┤', '┘', '┴', '└', '├', '┌', '┬', '┐'), ascii_symbols=('|', '/', '-', '\\')),
            progress_light                         = Symbol('━', '='),
            progress_heavy                         = Symbol('━', '='),
            progress_block                         = Symbol('▨', '#')
        )
    )